apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customercenter-hpa
  namespace: onlinebookstore
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customercenter
  targetCPUUtilizationPercentage: 70