apiVersion: v1
kind: Service
metadata:
  name: customercenter
  namespace: onlinebookstore
  labels:
    app: customercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customercenter